### ISSUE TITLE
Question: is a student-only project?

### ISSUE THREAD

**Issue by cosmos72** [PDZaninov/GoLang-Compiler#127]
Hello,

I am the author of https://github.com/cosmos72/gomacro, an almost complete Go interpreter written in Go, and I recently read about GraalVM.  
While evaluating whether GraalVM could be a good target for a Go compiler / JIT interpreter, I found your project and I have a question:

Is this a student-only project for an university course, or are you open to contributions?

Thanks,
Massimiliano Ghilardi (@cosmos72)

**Comment by kremmert** [comment]
Hi,

We will talk to our professor and sponsor and get back to you.

Thank you,
Kyle Remmert

**Comment by cosmos72** [comment]
Hi,
no hurry.

At this stage I am simply reading GraalVM docs and tutorials, and trying to understand whether it is well-suited for writing a Go compiler or Go JIT interpreter, instead of the "do everything manually" approach  I used in gomacro.

Clearly, your opinions from hands-on experience would help me understand faster :)

**Comment by PDZaninov** [comment]
Hi,

We are not accepting contributions at this time. We do not know enough to answer your question about whether it is well suited. We can say we haven't had too hard of a time using the Truffle API and does not require too much to get started.
